add_friend/urls.py
from django.conf.urls import url
from .views import index
from .views import add_friend

#url for app
urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'add_friend/$', add_friend, name='add_friend'),
]

app_home_status/urls.py
from django.conf.urls import url
from .views import index, tambah_status, comment, tambah_comment

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^tambah_status', tambah_status, name='tambah_status'),
    url(r'^comment/(?P<id>\w{0,50})/$', comment, name='comment'),
    url(r'^tambah_comment/(?P<id>\w{0,50})/$', tambah_comment, name='tambah_comment'),
]

app_profile_page/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

stat_dashboard_navbar_footer/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
	url(r'^$', index, name='index'),
]

tugas_1_ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_home_status.urls as app_home_status
import app_profile_page.urls as app_profile_page
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home-status/', include(app_home_status, namespace='home-status')),
    url(r'^profile-page/', include(app_profile_page,namespace='profile-page')),
    url(r'^$', RedirectView.as_view(url='home-status/', permanent='true'), name='index'),
]

add_friend/models.py
# # -*- coding: utf-8 -*-
# from __future__ import unicode_literals
# from django.db import models

# # Create your models here.
# class Friends(models.Model):
# 	name = models.CharField(max_length=30)
# 	URL = models.URLField()
# 	date = models.DateTimeField()

app_home_status/models.py
from django.db import models

class Status(models.Model):
    status = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

class Comments(models.Model):
    nama = models.TextField()
    comment = models.TextField()
    post = models.ForeignKey(Status, on_delete=models.CASCADE)
    comments_created_date = models.DateTimeField(auto_now_add=True)

app_profile_page/models.py
from django.db import models

class Profile(models.Model):
    name = models.CharField(max_length=120)
    gender = models.CharField(max_length=10)
    birth_date = models.DateField()
    email = models.EmailField()
    picture_url = models.URLField()
    expertise =  models.TextField()
    description = models.CharField(max_length=100)
    

stat_dashboard_navbar_footer/models.py
from django.db import models

# Create your models here.

app_home_status/forms.py
from django import forms

class Status_Form(forms.Form):
    status_attrs = {
        'placeholder':"Apa yang kamu pikirkan?",
        'class' : 'form-control',
        'type': 'text',
        'rows': 8,
        'style' : 'resize:none'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

class Comment_Form(forms.Form):
    nama_attrs = {
        'placeholder':"Berikan nama Anda :",
        'type': 'text',
        'class' : 'form-control',
        'rows': 1,
        'style' : 'resize:none'
    }
    comment_attrs = {
        'placeholder':"Berikan komentar Anda disini",
        'class' : 'form-control',
        'type': 'text',
        'rows': 4,
        'style' : 'resize:none'
    }
    comment = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=comment_attrs))
    nama = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=nama_attrs))
    
    

add_friend/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from .models import Friends
from datetime import datetime, date
from app_profile_page.active_profile import get_active_profile
import pytz
import json

# Create your views here.
friends_dict = {}

def index(request):
	friends_dict = Friends.objects.all().values()
	return render(request, 'friends_list.html', {'friends_dict' : friends_dict})
	
def add_friend(request):
	if request.method == 'POST':
		Friends.objects.create(name=request.POST['name'], URL=request.POST['URL'], date = datetime.now())
		add_friends()
		return redirect('/friends/')
	
def convert_queryset_into_json(queryset):
	ret_val = []
	for data in queryset:
		ret_val.append(data)
	return ret_val

app_home_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Status, Comments
from .forms import Status_Form, Comment_Form
from app_profile_page.profile import get_active_profile

# Create your views here.
response = {}

def index(request):
    profile = get_active_profile()
    status = Status.objects.order_by('-created_date')
    comments = Comments.objects.all()
    response['picture'] = profile.picture_url
    response['nama'] = profile.name
    response['status_form'] = Status_Form
    response['status'] = status
    response['comments'] = comments
    html = 'page_status.html'
    return render(request, html, response)

def comment(request,id):
    status = Status.objects.get(id=id)
    response['status'] = status
    response['comment_form'] = Comment_Form
    html = 'page_comment.html'
    return render(request, html, response)

def tambah_status(request):
    response['status'] = request.POST['status']
    status = Status(status=response['status'])
    status.save()
    return HttpResponseRedirect('/home-status')

def tambah_comment(request,id):
    response['adding_comment'] = request.POST['comment']
    response['nama'] = request.POST['nama']
    response['status'] = Status.objects.get(id=id)
    comment = Comments(comment = response['adding_comment'], nama = response['nama'],  post = response['status'])
    comment.save()
    return HttpResponseRedirect('/home-status')

app_profile_page/views.py
from django.shortcuts import render
from datetime import datetime, date
from .profile import get_active_profile

exp = ['QA', 'Tester', 'Project Manageer']
def index(request):

    profile = get_active_profile()
    response = {'name': profile.name, 'gender': profile.gender,'birth': profile.birth_date,
                'email': profile.email,'picture': profile.picture_url,'expertise': exp,
                'description': profile.description}
    return render(request, 'profile_page.html', response)

stat_dashboard_navbar_footer/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from app_profile_page.active_profile import get_active_profile
# Create your views here.
response = {} 

def index(request):
	author="kelompok E: Ester, median, Rizki, naufal"
	status = Status.objects.order_by('-created_date')
	comments = Comments.objects.all()
	response['picture'] = profile.picture_url
	response['nama'] = profile.name
	response['status_form'] = Status_Form
	response['comments'] = comments
	response['friends'] = friends
	response['post']= post
	response['author']=author
	num1=1
	for x in status():
		if num1==post:
			status=x
		num1=num1+1
	response['status'] = status
	html = 'stats.html'
	return render(request, html, response)

tugas_1_ppw/views.py
from django.shortcuts import render, HttpResponsePermanentRedirect

#TODO Implement
#Create a content paragraph for your landing page:

def index(request):
    return HttpResponsePermanentRedirect('/home-status')

add_friend/templates/friends_list.html
{% extends "base.html" %}
{% block content %}
<h3>Add Friend</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_friend/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Name:
                    </td>
                    <td>
                        <input type="text" name="Name" class="form-control" maxlength="27" required>
                    </td>
                </tr>
                <tr>
                    <td>
                        URL:
                    </td>
                    <td>
                        <input type="url" name="URL" required>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Add Friend</button>
        </form>
    </div>
    <div class="col-md-6 col-xs-6">
        <table>
            <tr>
                <th>List Friend</th>
            </tr>
            {% for friends_data in friends_dict %}
                <tr>
                    <td class="name">{{ friends_data.name }}</td>
                    <td class="URL">{{ friends_data.URL }}</td>
                    <td class="date">{{ friends_data.date }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

app_home_status/templates/page_comment.html
{% extends "templates/base.html" %}

{% block content %}

<div class = "container">
    <section name="update_status" id="update_status">
        <form id="form" method="POST" action="{% url 'home-status:tambah_comment' status.id %}">
            <h3>Update Status</h3>
            {% csrf_token %}
            {{ comment_form }}
            <br>
            <input class="btn btn-default btn-primary" type="submit" value="Post" style="float: right;">
            <br>
        </form>
        <br>
    </section>
</div>
{% endblock %}

app_home_status/templates/page_status.html
{% extends "templates/base.html" %}

{% block content %}

<style>
.font1{
    font-family: 'Spectral SC', serif;
}
.part2-info_user .glyphicon-user{
	font-size: 150px;
    color: red
}
.buttonPertama{
	margin-bottom: 20px;
}
.myData{
	
	padding: 10px;
}
.part2 a{
	margin-bottom: 30px;
	margin-left: 30px;
}
.part2_info_user{
	background-color: #C8D8DE;
	padding: 10px;
	border-radius: 10px;
}
.media-left .glyphicon-user{
font-size: 50px;
margin-right: 30px;
}
.kotak{
background-color: #F0FFFF;
border-radius: 30px;
margin-bottom: 20px;
}
.page1{
    top: -120px;
}
.row .btn-danger{
    margin-top: 40px;
}
  </style>

<!-- bikin konten buat tiap fitur di sini yak-->
<div class = "container" id="container-status">
    <section name="update_status" id="update_status">
        <form id="form" method="POST" action="{% url 'home-status:tambah_status' %}">
            <h3>Input Status</h3>
            {% csrf_token %}
            {{ status_form }}
            <br>
            <input id="submit" type="submit" class="btn btn-default btn-primary" value="Post" style="float: right;">
            <br>
        </form>
        <br>
    </section>
	
    <section name ="status_history" id = "status_history">
        <div class="container">
            {% for i in status %}
            <div class="kotak" style="padding-top: 10px">
			<div class="row">
                <div class="col-sm-8">
                    <div class="media" style="padding: 10px">
                        <div class="media-left ">
                            <img src="https://c2.staticflickr.com/4/3006/2649581844_984d2a084a_b.jpg" alt="gambar" width = "55px" height = "55px" style="border-radius:50%">
						</div>
                    </div>
                    <div class="media-heading" style="padding-left:15px;margin-top:10px;width:87%">
                        <b> {{ nama }}</b>
                        <p class = "media-heading" style="font-size: 15px;word-wrap:break-word;">
                                {{ i.status | linebreaksbr }}
                        </p>
                        <div id="created_date" style="font-size:80%; font-style:italic;margin-bottom:5px; color: black" align="left"> {{ i.created_date | date:"d M Y H:i:s" }}</div>
                        <div class="adding-comment-link" align="left">
                            <a href="{% url 'home-status:comment' i.id %}" style="color: black;font-size:85%;">
                                Add Comment
                            </a>
                        </div>
                    </div>
                </div>
            </div>
			{% for data in comments %}
			{% if data.post.id == i.id %}
			<div class="row">
			<div class="col-sm-8">
				<div class="media" style="padding: 10px">
					<div class="media-left ">
						<img src="{{picture}}" alt="gambar" align="left" width = "50px" height = "50px" style="border-radius:50%">
					</div>
				</div>
			</div>
				<div class="media" align="left" style="width: 87%;padding-left:15px;margin-top:10px">
						<b>{{data.nama}}</b>
						<p class="media-heading" style="padding-left:15px;margin-top:10px;width:87%">
						{{ data.comment | linebreaksbr }} </p>
					<div id="created_date" style="font-size:80%; font-style:italic;margin-bottom:5px; color: black"> 
						{{ data.comments_created_date | date:"d M Y H:i:s" }}
					</div>
				</div>
			</div>
			<br>
			    {% endif %}
                {% endfor %}
			</div>
            {% endfor %}
            </div>
        </div>
    </section>
</div>
{% endblock %}

app_home_status/templates/templates/base.html
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:th="http://www.thymeleaf.org">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<link rel="stylesheet" href="/css/bootstrap.min.css" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></link>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<style>
			ul {
    			list-style-type: none;
    			margin: 0;
    			padding: 0;
    			overflow: hidden;
    			background-color: #E9967A;
			}

			li {
    			float: left;
			}

			li a {
    			display: block;
    			color: 	#FFF8DC;
    			text-align: center;
    			padding: 20px 30px;
    			text-decoration: none;
				font-size : 20px;
				font face : verdana;
			}

			li a:hover {
    			background-color: #FFF8DC;
			}
			
			.button {
				background-color: blue;
				font-size: 15px;
				color: white;
				margin: 5px 0px;
			}
			
		</style>
	</head>

	<body style ="background-color : yellow">
		
		<ul>
			<li><a href="{% url 'home-status:index' %}">Ling In</a></li>
  			<li><a class="active" href="{% url 'home-status:index' %}">Status</a></li>
		  <li>
			<a class="nav-link" href="#">Profile</a>
		  </li>
		    <li><a href="#cari">Profile</a></li>
			<li><a href="#cari">Friends</a></li>
			<li><a href="#cari">Statistic</a></li>
		</ul>
		
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
		
	</body>

</html>

app_profile_page/templates/profile_page.html
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:th="http://www.thymeleaf.org">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<link rel="stylesheet" href="/css/bootstrap.min.css" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"></link>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<style>
			ul {
    			list-style-type: none;
    			margin: 0;
    			padding: 0;
    			overflow: hidden;
    			background-color: #E9967A;
			}

			li {
    			float: left;
			}

			li a {
    			display: block;
    			color: 	#FFF8DC;
    			text-align: center;
    			padding: 20px 30px;
    			text-decoration: none;
				font-size : 20px;
				font face : verdana;
			}

			li a:hover {
    			background-color: #FFF8DC;
			}
			
			.button {
				background-color: blue;
				font-size: 15px;
				color: white;
				margin: 5px 0px;
			}
			
		</style>
	</head>

	<body style ="background-color : yellow">
		
		<ul>
			<li><a href="{% url 'home-status:index' %}">Ling In</a></li>
  			<li><a class="active" href="{% url 'home-status:index' %}">Status</a></li>
		  <li>
			<a class="nav-link" href="#">Profile</a>
		  </li>
		    <li><a href="#cari">Profile</a></li>
			<li><a href="#cari">Friends</a></li>
			<li><a href="#cari">Statistic</a></li>
		</ul>
		
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
		
	</body>

</html>

stat_dashboard_navbar_footer/templates/stats.html
<!-- {% extends "lab_4/layout/base.html" %}
{% block content %}
<p>    Statistic</p>
<section name="photo">
	<b>{{nama}}</b>
</section>
<section name="information">
	<p><b>Friends     </b>{{friends}} People                <b>Feed</b>     {{post}} Post</p>
	<br><p>Latest Post</p><br>
</section>
<hr/>
<section name="timeline">
	<div class="container">
		<div class="kotak" style="padding-top: 10px">
		<div class="row">
			<div class="col-sm-8">
				<div class="media" style="padding: 10px">
					<div class="media-left ">
						<img src="https://c2.staticflickr.com/4/3006/2649581844_984d2a084a_b.jpg" alt="gambar" width = "55px" height = "55px" style="border-radius:50%">
					</div>
				</div>
				<div class="media-heading" style="padding-left:15px;margin-top:10px;width:87%">
					<b> {{ nama }}</b>
					<p class = "media-heading" style="font-size: 15px;word-wrap:break-word;">
							{{ status | linebreaksbr }}
					</p>
					<div id="created_date" style="font-size:80%; font-style:italic;margin-bottom:5px; color: black" align="left"> {{ i.created_date | date:"d M Y H:i:s" }}</div>
				</div>
			</div>
		</div>
		<br>
		</div>
		{% endfor %}
		</div>
	</div>
</section>
{% endblock %}
 -->